spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sputnik_core
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

redis:
  host: localhost
  port: 6379

jwt:
  secret: your_jwt_secret
  expiration: 86400  # 1 day in seconds

logging:
  level:
    root: INFO
    com.sputnik.core: DEBUG

spring:
  security:
    user:
      name: admin
      password: admin_password
      roles: ADMIN